# Create account
POST http://localhost:9000/accounts
content-type: application/json

{
    "owner": "nam.nguyen",
    "currency": "USD"
}

###
# Get account
GET http://localhost:9000/accounts/23

###
# Get list account
GET http://localhost:9000/accounts?page_id=30&page_size=20
